### ISSUE TITLE
Constraints being loosened by boundary

### ISSUE THREAD

**Issue by shyndman** [rrousselGit/boundary#3]
I actually encountered this awhile back, but it slipped my mind to report...but then it popped back in, so here I am. :)

The `Stack` being used in the boundary is modifying constraints, so when the boundary is applied, a widget will sometimes render differently than it would without.

I encountered this with a situation similar to:

* Stack
  * Positioned.fromRect // tight constraints
    * Boundary // constraints loosened
      * DecoratedBox // sizes to zero

I suspect this isn't desired. If you agree, happy to send a PR.

I'm finding this very useful, btw. We work with widgets that can't be trusted, and boundary is keeping them in line.

**Comment by rrousselGit** [comment]
Sure, feel free to make a PR

But honestly, this needs a rewrite of the internals. 

In reality, it probably needs to work like https://github.com/rrousselGit/flutter_portal instead of relying on tricks around Element.

That is, use a custom RenderObject, pass max tight constraints to the child, play around `paint` and `hitTest`


This should be both more performant and more reliable

**Comment by shyndman** [comment]
If you decide to go down that route, I would happily use it. There's a _lot_ of boundary in our application.

But honestly, its impact on runtime performance is negligable for our use case. We set these things up, then leave them for the most part. They're almost never updated or torn down.

But _anyway_, I'll put together a PR. 

Hmm...flutter_portal is cool.
